BEGIN TRANSACTION;
CREATE TABLE todo_users (
    id TEXT PRIMARY KEY,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    content TEXT
);
COMMIT;
